"""rename department

Revision ID: 964f6c248cf0
Revises: 9e79d6d0d25d
Create Date: 2023-11-12 17:19:24.192859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "964f6c248cf0"
down_revision = "9e79d6d0d25d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
    # ### end Alembic commands ###
